### ISSUE TITLE
Feeder Scan Not Working

### ISSUE THREAD

**Issue by Amplifier47** [neodynamic/JSPrintManager-Blazor#2]
While testing JSPM out, I found that printing and flatbed scanning seem to work fine, but when I check the 'Enable Feeder' checkbox (also tried on the demo page) it still scans from the flatbed. I played around with the Feeder Count (including values 0, 1, 50), but no difference.

Here is an image with the settings I tried
![chrome_oTbebSSaSi](https://user-images.githubusercontent.com/83319963/196455218-7b64b596-56dd-41bf-837f-b471fbc841a5.png)

To make sure the feeder on my printer works, I did several successful feeder scans from the 'Scan' app on the same computer as in the previous tests.

My Specs:
OS: Windows 11 Pro       Version: 22H2
Sofware: jspm5-5.0.22.801-win32.exe   (32-bit version of JSPM for Windows)
Printer: Brother DCP-7065DN  (It has a feeder)
License: NONE

**Comment by neodynamic** [comment]
That scanner seems to have a WIA driver and the feeder feature of our product is supported for TWAIN drivers... don't if brother has a TWAIN driver for that model

**Comment by Amplifier47** [comment]
Ok I must have missed that when researching this.

Thank you for the quick response.
